-- Feb 19, 2024
-- update qp-target-gene command name to "QIIMEq2" to be in sync with plugin repo
--    When setting up a new instance of Qiita, we end up using qiita-env make
--    which creates entries in the postgress database, also for qiita.software.
--    One of these entries belongs to the qp-target-gene plugin with name "QIIME"
--    and version "1.9.1". However, with 
--    qp_target_gene/support_files/patches/171029_QIIME_v191_to_QIIMEq2_v191.sql
--    the plugin was renamed into QIIMEq2, but this change was not relected in
--    the qiita.software table. Thus, updating plugin information finds a mismatch
--    between old (QIIME) and new (QIIMEq2) names and therefor creates a new
--    command. However, the also provided default workflows hold command_ids to
--    the old version and subsequently the commands for artifact processing
--    will result in an empty list, even though the plugin is available.
--    Therefore, this patch updates the name of QIIME.
UPDATE qiita.software SET name = 'QIIMEq2' WHERE name = 'QIIME';
