#!/usr/bin/env bash

qiita-cron-job empty-trash-upload-folder
qiita-cron-job generate-biom-and-metadata-release
qiita-cron-job purge-filepaths
qiita-cron-job purge-files-from-filesystem
qiita-cron-job update-redis-stats
qiita-cron-job generate-plugin-releases
