#!/bin/sh

# -----------------------------------------------------------------------------
# Copyright (c) 2014, The Qiita Development Team.
#
# Distributed under the terms of the BSD 3-clause License.
#
# The full license is in the file LICENSE, distributed with this software.
# -----------------------------------------------------------------------------

exec pyqi --driver-name qiita_db --command-config-module qiita_db.interfaces.optparse.config -- "$@"