#!/usr/bin/env python

# -----------------------------------------------------------------------------
# Copyright (c) 2014--, The Qiita Development Team.
#
# Distributed under the terms of the BSD 3-clause License.
#
# The full license is in the file LICENSE, distributed with this software.
# -----------------------------------------------------------------------------

import click

from qiita_db.environment_manager import (make_test_environment,
                                          make_production_environment,
                                          drop_test_environment,
                                          clean_test_environment,
                                          DFLT_BASE_DATA_FOLDER,
                                          DFLT_BASE_WORK_FOLDER)
from qiita_db.util import get_filetypes
from qiita_db.data import load_raw, load_preprocessed, load_processed

@click.group()
def qiita_db():
    pass


@click.command()
@click.option('--base_data_folder', default=DFLT_BASE_DATA_FOLDER,
              help="The folder where the test data files are stored")
@click.option('--base_work_folder', default=DFLT_BASE_WORK_FOLDER,
              help="The folder where the actively worked on files are stored")
@click.option('--user', default='postgres',
              help="The database user to connect to the database")
@click.option('--host', default='localhost',
              help='The host where the database lives')
def make_test_env(base_data_folder, base_work_folder, user, host):
    """Creates a test database environment.

    Creates a new database called `qiita_test` tailored for testing purposes
    and initializes the `settings` table of such database
    """
    make_test_environment(base_data_folder, base_work_folder, user, None, host)


@click.command()
@click.option('--user', default='postgres',
              help="The database user to connect to the database")
@click.option('--host', default='localhost',
              help='The host where the database lives')
def clean_test_env(user, host):
    """Cleans the test database environment.

    In case that the test database is dirty (i.e. the 'qiita' schema is
    present), this cleans it up by dropping the 'qiita' schema.
    """
    clean_test_environment(user, None, host)


@click.command()
@click.option('--user', default='postgres',
              help="The database user to connect to the database")
@click.option('--host', default='localhost',
              help='The host where the database lives')
def drop_test_env(user, host):
    """Drops the test database environment.

    If the `settings` table is modified, the test database environment should
    be rebuilt. This command allows to drop the old one.
    """
    drop_test_environment(user, None, host)


@click.command()
def make_production_env():
    """TODO: Not implemented"""
    make_production_environment()

@click.command()
@click.option('--fp', required=True, type=click.Path, exists=True,
              readable=True, resolve_path=True, multiple=True,
              help='Path to the raw data file. This option can be used '
              'multiple times if there are multiple raw data files.')
@click.option('--filetype', require=True,
              type=click.Choice(get_filetypes().keys()),
              help='The type of data')
@click.option('--study', required=True, multiple=True, help='Associate the '
              'data with this study. This option can be used multiple times '
              'if the data should be associated with multiple studies')
def load_raw_data(fp, filetype, study):
    data.load_raw(fp, filetype, study)


qiita_db.add_command(make_test_env)
qiita_db.add_command(clean_test_env)
qiita_db.add_command(drop_test_env)
qiita_db.add_command(make_production_env)
qiita_db.add_command(load_raw_data)

if __name__ == '__main__':
    qiita_db()
