#!/usr/bin/env python

# -----------------------------------------------------------------------------
# Copyright (c) 2014--, The Qiita Development Team.
#
# Distributed under the terms of the BSD 3-clause License.
#
# The full license is in the file LICENSE, distributed with this software.
# -----------------------------------------------------------------------------

import click

from qiita_db.util import get_filetypes, get_filepath_types
from qiita_db.commands import make_study_from_cmd, load_raw_data_cmd


@click.group()
def qiita_db():
    pass


@qiita_db.command()
@click.option('--fp', required=True, type=click.Path(resolve_path=True,
              readable=True, exists=True), multiple=True,
              help='Path to the raw data file. This option can be used '
              'multiple times if there are multiple raw data files.')
@click.option('--fp_type', required=True, multiple=True, help='Describes the '
              'contents of the file. Pass one fp_type per fp.',
              type=click.Choice(get_filepath_types().keys()))
@click.option('--filetype', required=True,
              type=click.Choice(get_filetypes().keys()),
              help='The type of data')
@click.option('--study', multiple=True, help='Associate the data with this '
              'study. This option can be used multiple times if the data '
              'should be associated with multiple studies')
def load_raw_data(fp, fp_type, filetype, study):
    data.load_raw_cmd(fp, filetype, study)


@qiita_db.command()
@click.option('--owner', help="The email address of the owner of the study")
@click.option('--title', help="The title of the study")
@click.option('--info', type=click.File(mode='r'),
              help="filepath of file with study information in python"
              "config file format")
def insert_study_to_db(owner, title, info):
    make_study_from_cmd(owner, title, info)


if __name__ == '__main__':
    qiita_db()
